version: '3.9'
services:
  postgres:
    image: postgres:15
    container_name: demo-postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: demo_db
    ports:
      - "5432:5432"
